### ISSUE TITLE
[BUG] JsonType isn't in the jar file

### ISSUE THREAD

**Issue by stopachka** [google/cel-java#146]
**Describe the bug**
I see that we have a `dev.cel.common.types.JsonType`. But this does not seem to be found in the JAR file. 

It looks like in the build file JsonType is in a separate [build declaration](https://github.com/google/cel-java/blob/1520cfe1370ea4e390c87633204a7f6b72a152a0/common/src/main/java/dev/cel/common/types/BUILD.bazel#L99), but it isn't required in the main `cel` [build declaration](https://github.com/google/cel-java/blob/1520cfe1370ea4e390c87633204a7f6b72a152a0/bundle/src/main/java/dev/cel/bundle/BUILD.bazel#L31). This may be the cause. Was this intended, or is it a bug?

**Expected behavior**
I should be able to import dev.cel.common.types.JsonType 

--- 

cel is so awesome! Great work team.

**Comment by l46kok** [comment]
Hi, this was an intentional omission because `dev.cel.common.types.JsonType` doesn't really do anything today. 

Currently, support for JSON is achieved via the `google.protobuf.Value` message type (true for all CEL libraries). We plan on introducing JSON as a first-class citizen type in the future to avoid the protobuf dependency. We'll add it to the JAR once this capability has been added.

**Comment by stopachka** [comment]
Understood! Hack on and can’t wait for the updates to come in :).
