### ISSUE TITLE
Maven packaging conflicts

### ISSUE THREAD

**Issue by MBloom** [google/cel-java#164]
I am running into package conflicts when building a project using bazel. Specifically, I have noted the following conflicts between these two packages:
* https://mvnrepository.com/artifact/com.google.api.grpc/proto-google-common-protos/1.17.0
* https://mvnrepository.com/artifact/dev.cel/cel/0.2.0

I've been able to trace the conflicts based on the following:
* https://github.com/google/cel-java/blob/v0.2.0/WORKSPACE#L96
  An `http_archive` that pulls in an untagged commit from 2022 on the `master` branch of `com_google_googleapis`) -- i.e. :point_down: this one
* [https://github.com/googleapis/googleapis/blob/d73a4161.../google/rpc/BUILD.bazel#L40](https://github.com/googleapis/googleapis/blob/d73a41615b101c34c58b3534c2cc7ee1d89cccb0/google/rpc/BUILD.bazel#L40)
  a `java_proto_library` that defines the proto-generated classes under `com.google.rpc`
* https://github.com/google/cel-java/blob/v0.2.0/common/src/test/java/dev/cel/common/CelDescriptorUtilTest.java
  One of a handful of test code that uses classes from `com.google.rpc`

There isn't an easy work around for this due to the fact that the maven dependency is hard coded into the cel-java files.

**Comment by l46kok** [comment]
Hi,

The reason for bringing `com_google_googleapis` directly is that we needed to bring in [v1alpha1 protos](https://github.com/googleapis/googleapis/tree/master/google/api/expr/v1alpha1) that only exists in that repo. 

What I can probably do is separate out the dependencies so that `com.google.rpc` is served from a tagged maven dependency while leaving the `com.google.api.expr` to be pulled from googleapis repo. Let me know if that helps.

https://github.com/google/cel-java/pull/165 is the change I'm proposing.

**Comment by MBloom** [comment]
That is a reasonable fix for the time being. However, I'd imagine a more sustainable long-term solution would be to move those dependencies to a shared library (e.g. `proto-google-common-protos`) that can be managed via a maven dependency.

**Comment by MBloom** [comment]
@l46kok We're still blocked from using this library due to maven conflicts. Is any work planned to migrate these packages to be managed using maven instead of being hardcoded and merged directly into the jar?

**Comment by MBloom** [comment]
Ah sorry, disregard. I'm able to get this to work using `v0.4.0`.
