### ISSUE TITLE
protobuf dependency version problem

### ISSUE THREAD

**Issue by wang-qijia** [google/cel-java#353]
Does cel-java have to depend on protobuf-java? In my project, protobuf uses 2.5.0 and cel uses 3.25.3. Finally, there is a dependency conflict. Is there a solution to this? Thanks

**Comment by l46kok** [comment]
Presently, protobuf is a required dependency for CEL. This is primarily because [CEL specification is protobuf-centric](https://github.com/google/cel-spec/blob/master/doc/langdef.md). We do have long-term plans to make protobuf an optional dependency in the future, but I don't have any timelines I can share as of now.

For now, you'll have to follow any standard mechanism available in your build-tool to address the version conflict.
